from django.urls import path

from .views import (
    AppointmentCreateView,
    AppointmentDeleteView,
    AppointmentDetailView,
    AppointmentCalendarView,
    AppointmentCheckInView,
    AppointmentListView,
    AppointmentTicketPDFView,
    AppointmentUpdateView,
    ClinicHolidayCreateView,
    ClinicHolidayDeleteView,
    ClinicHolidayListView,
    ClinicHolidayUpdateView,
    DoctorScheduleCreateView,
    DoctorScheduleDeleteView,
    DoctorScheduleListView,
    DoctorScheduleUpdateView,
    InvoiceCreateView,
    InvoiceDeleteView,
    InvoiceDetailView,
    InvoiceItemCreateView,
    InvoiceItemDeleteView,
    InvoiceItemUpdateView,
    InvoiceListView,
    InvoicePDFView,
    InvoiceUpdateView,
    MedicineCreateView,
    MedicineDeleteView,
    MedicineDetailView,
    MedicineListView,
    MedicineUpdateView,
    PatientCreateView,
    PatientDeleteView,
    PatientDetailView,
    PatientListView,
    PatientUpdateView,
    MoMoIPNView,
    MoMoPaymentCreateView,
    MoMoReturnView,
    MoMoSimulationView,
    PaymentCreateView,
    PaymentDeleteView,
    PaymentTransactionDetailView,
    PaymentTransactionQueryView,
    PaymentUpdateView,
    PriceListCreateView,
    PriceListDeleteView,
    PriceListDetailView,
    PriceListListView,
    PriceListUpdateView,
    ReceptionTodayView,
    ReceptionWalkInCreateView,
    PrescriptionCreateView,
    PrescriptionDeleteView,
    PrescriptionDetailView,
    PrescriptionItemCreateView,
    PrescriptionItemDeleteView,
    PrescriptionItemUpdateView,
    PrescriptionListView,
    PrescriptionUpdateView,
    ServiceCategoryCreateView,
    ServiceCategoryDeleteView,
    ServiceCategoryDetailView,
    ServiceCategoryListView,
    ServiceCategoryUpdateView,
    ServiceCreateView,
    ServiceDeleteView,
    ServiceDetailView,
    ServiceListView,
    ServicePriceCreateView,
    ServicePriceDeleteView,
    ServicePriceUpdateView,
    ServiceUpdateView,
    StaffCreateView,
    StaffDeleteView,
    StaffDetailView,
    StaffListView,
    StaffUpdateView,
    StaffConversationAssignView,
    StaffConversationCloseView,
    StaffConversationDetailView,
    StaffConversationListView,
    StaffMessagePollView,
    StaffMessageSendView,
    SupplyCreateView,
    SupplyDeleteView,
    SupplyDetailView,
    SupplyExportCreateView,
    SupplyExportDeleteView,
    SupplyExportUpdateView,
    SupplyListView,
    SupplyLotCreateView,
    SupplyLotDeleteView,
    SupplyLotUpdateView,
    SupplyUpdateView,
    SystemDashboardView,
    WorkShiftCreateView,
    WorkShiftDeleteView,
    WorkShiftListView,
    WorkShiftUpdateView,
)

app_name = "clinic"

urlpatterns = [
    path("", SystemDashboardView.as_view(), name="dashboard"),
    # Bệnh nhân
    path("patients/", PatientListView.as_view(), name="patient-list"),
    path("patients/create/", PatientCreateView.as_view(), name="patient-create"),
    path("patients/<int:pk>/", PatientDetailView.as_view(), name="patient-detail"),
    path("patients/<int:pk>/edit/", PatientUpdateView.as_view(), name="patient-update"),
    path("patients/<int:pk>/delete/", PatientDeleteView.as_view(), name="patient-delete"),
    # Nhân viên / bác sĩ
    path("staff/", StaffListView.as_view(), name="staff-list"),
    path("staff/create/", StaffCreateView.as_view(), name="staff-create"),
    path("staff/<int:pk>/", StaffDetailView.as_view(), name="staff-detail"),
    path("staff/<int:pk>/edit/", StaffUpdateView.as_view(), name="staff-update"),
    path("staff/<int:pk>/delete/", StaffDeleteView.as_view(), name="staff-delete"),
    path("service-categories/", ServiceCategoryListView.as_view(), name="service-category-list"),
    path("service-categories/create/", ServiceCategoryCreateView.as_view(), name="service-category-create"),
    path("service-categories/<int:pk>/", ServiceCategoryDetailView.as_view(), name="service-category-detail"),
    path("service-categories/<int:pk>/edit/", ServiceCategoryUpdateView.as_view(), name="service-category-update"),
    path("service-categories/<int:pk>/delete/", ServiceCategoryDeleteView.as_view(), name="service-category-delete"),
    path("services/", ServiceListView.as_view(), name="service-list"),
    path("services/create/", ServiceCreateView.as_view(), name="service-create"),
    path("services/<int:pk>/", ServiceDetailView.as_view(), name="service-detail"),
    path("services/<int:pk>/edit/", ServiceUpdateView.as_view(), name="service-update"),
    path("services/<int:pk>/delete/", ServiceDeleteView.as_view(), name="service-delete"),
    path("price-lists/", PriceListListView.as_view(), name="price-list-list"),
    path("price-lists/create/", PriceListCreateView.as_view(), name="price-list-create"),
    path("price-lists/<int:pk>/", PriceListDetailView.as_view(), name="price-list-detail"),
    path("price-lists/<int:pk>/edit/", PriceListUpdateView.as_view(), name="price-list-update"),
    path("price-lists/<int:pk>/delete/", PriceListDeleteView.as_view(), name="price-list-delete"),
    path("price-lists/<int:price_list_pk>/prices/create/", ServicePriceCreateView.as_view(), name="service-price-create"),
    path("service-prices/<int:pk>/edit/", ServicePriceUpdateView.as_view(), name="service-price-update"),
    path("service-prices/<int:pk>/delete/", ServicePriceDeleteView.as_view(), name="service-price-delete"),
    # Thanh toán và hóa đơn
    path("invoices/", InvoiceListView.as_view(), name="invoice-list"),
    path("invoices/create/", InvoiceCreateView.as_view(), name="invoice-create"),
    path("invoices/<int:pk>/", InvoiceDetailView.as_view(), name="invoice-detail"),
    path("invoices/<int:pk>/edit/", InvoiceUpdateView.as_view(), name="invoice-update"),
    path("invoices/<int:pk>/delete/", InvoiceDeleteView.as_view(), name="invoice-delete"),
    path("invoices/<int:pk>/pdf/", InvoicePDFView.as_view(), name="invoice-pdf"),
    path("invoices/<int:invoice_pk>/momo/", MoMoPaymentCreateView.as_view(), name="momo-payment-create"),
    path("invoices/<int:invoice_pk>/items/create/", InvoiceItemCreateView.as_view(), name="invoice-item-create"),
    path("invoice-items/<int:pk>/edit/", InvoiceItemUpdateView.as_view(), name="invoice-item-update"),
    path("invoice-items/<int:pk>/delete/", InvoiceItemDeleteView.as_view(), name="invoice-item-delete"),
    path("invoices/<int:invoice_pk>/payments/create/", PaymentCreateView.as_view(), name="payment-create"),
    path("payment-transactions/<int:pk>/", PaymentTransactionDetailView.as_view(), name="payment-transaction-detail"),
    path("payment-transactions/<int:pk>/query/", PaymentTransactionQueryView.as_view(), name="payment-transaction-query"),
    path("payments/momo/return/", MoMoReturnView.as_view(), name="momo-return"),
    path("payments/momo/ipn/", MoMoIPNView.as_view(), name="momo-ipn"),
    path("payments/momo/simulate/<int:pk>/", MoMoSimulationView.as_view(), name="momo-simulate-payment"),
    path("payments/<int:pk>/edit/", PaymentUpdateView.as_view(), name="payment-update"),
    path("payments/<int:pk>/delete/", PaymentDeleteView.as_view(), name="payment-delete"),
    # Thuốc và đơn thuốc
    path("medicines/", MedicineListView.as_view(), name="medicine-list"),
    path("medicines/create/", MedicineCreateView.as_view(), name="medicine-create"),
    path("medicines/<int:pk>/", MedicineDetailView.as_view(), name="medicine-detail"),
    path("medicines/<int:pk>/edit/", MedicineUpdateView.as_view(), name="medicine-update"),
    path("medicines/<int:pk>/delete/", MedicineDeleteView.as_view(), name="medicine-delete"),
    path("prescriptions/", PrescriptionListView.as_view(), name="prescription-list"),
    path("prescriptions/create/", PrescriptionCreateView.as_view(), name="prescription-create"),
    path("prescriptions/<int:pk>/", PrescriptionDetailView.as_view(), name="prescription-detail"),
    path("prescriptions/<int:pk>/edit/", PrescriptionUpdateView.as_view(), name="prescription-update"),
    path("prescriptions/<int:pk>/delete/", PrescriptionDeleteView.as_view(), name="prescription-delete"),
    path(
        "prescriptions/<int:prescription_pk>/items/create/",
        PrescriptionItemCreateView.as_view(),
        name="prescription-item-create",
    ),
    path("prescription-items/<int:pk>/edit/", PrescriptionItemUpdateView.as_view(), name="prescription-item-update"),
    path("prescription-items/<int:pk>/delete/", PrescriptionItemDeleteView.as_view(), name="prescription-item-delete"),
    # Vật tư / kho
    path("supplies/", SupplyListView.as_view(), name="supply-list"),
    path("supplies/create/", SupplyCreateView.as_view(), name="supply-create"),
    path("supplies/<int:pk>/", SupplyDetailView.as_view(), name="supply-detail"),
    path("supplies/<int:pk>/edit/", SupplyUpdateView.as_view(), name="supply-update"),
    path("supplies/<int:pk>/delete/", SupplyDeleteView.as_view(), name="supply-delete"),
    path("supplies/<int:supply_pk>/lots/create/", SupplyLotCreateView.as_view(), name="supply-lot-create"),
    path("supply-lots/<int:pk>/edit/", SupplyLotUpdateView.as_view(), name="supply-lot-update"),
    path("supply-lots/<int:pk>/delete/", SupplyLotDeleteView.as_view(), name="supply-lot-delete"),
    path("supplies/<int:supply_pk>/exports/create/", SupplyExportCreateView.as_view(), name="supply-export-create"),
    path("supply-exports/<int:pk>/edit/", SupplyExportUpdateView.as_view(), name="supply-export-update"),
    path("supply-exports/<int:pk>/delete/", SupplyExportDeleteView.as_view(), name="supply-export-delete"),
    # Lịch khám
    path("holidays/", ClinicHolidayListView.as_view(), name="holiday-list"),
    path("holidays/create/", ClinicHolidayCreateView.as_view(), name="holiday-create"),
    path("holidays/<int:pk>/edit/", ClinicHolidayUpdateView.as_view(), name="holiday-update"),
    path("holidays/<int:pk>/delete/", ClinicHolidayDeleteView.as_view(), name="holiday-delete"),
    path("work-shifts/", WorkShiftListView.as_view(), name="work-shift-list"),
    path("work-shifts/create/", WorkShiftCreateView.as_view(), name="work-shift-create"),
    path("work-shifts/<int:pk>/edit/", WorkShiftUpdateView.as_view(), name="work-shift-update"),
    path("work-shifts/<int:pk>/delete/", WorkShiftDeleteView.as_view(), name="work-shift-delete"),
    path("doctor-schedules/", DoctorScheduleListView.as_view(), name="doctor-schedule-list"),
    path("doctor-schedules/create/", DoctorScheduleCreateView.as_view(), name="doctor-schedule-create"),
    path("doctor-schedules/<int:pk>/edit/", DoctorScheduleUpdateView.as_view(), name="doctor-schedule-update"),
    path("doctor-schedules/<int:pk>/delete/", DoctorScheduleDeleteView.as_view(), name="doctor-schedule-delete"),
    path("reception/today/", ReceptionTodayView.as_view(), name="reception-today"),
    path("reception/walk-ins/create/", ReceptionWalkInCreateView.as_view(), name="reception-walk-in-create"),
    path("appointments/<int:pk>/check-in/", AppointmentCheckInView.as_view(), name="appointment-check-in"),
    path("appointments/<int:pk>/ticket/", AppointmentTicketPDFView.as_view(), name="appointment-ticket"),
    path("appointments/", AppointmentListView.as_view(), name="appointment-list"),
    path("appointments/calendar/", AppointmentCalendarView.as_view(), name="appointment-calendar"),
    path("appointments/create/", AppointmentCreateView.as_view(), name="appointment-create"),
    path("appointments/<int:pk>/", AppointmentDetailView.as_view(), name="appointment-detail"),
    path("appointments/<int:pk>/edit/", AppointmentUpdateView.as_view(), name="appointment-update"),
    path("appointments/<int:pk>/delete/", AppointmentDeleteView.as_view(), name="appointment-delete"),
    # Tin nhắn hỗ trợ
    path("messages/", StaffConversationListView.as_view(), name="conversation-list"),
    path("messages/<int:pk>/", StaffConversationDetailView.as_view(), name="conversation-detail"),
    path("messages/<int:pk>/send/", StaffMessageSendView.as_view(), name="conversation-send"),
    path("messages/<int:pk>/poll/", StaffMessagePollView.as_view(), name="conversation-poll"),
    path("messages/<int:pk>/assign/", StaffConversationAssignView.as_view(), name="conversation-assign"),
    path("messages/<int:pk>/close/", StaffConversationCloseView.as_view(), name="conversation-close"),
]
