# Generated by Django 4.2.24 on 2026-06-05 08:35

from django.db import migrations


def delete_cashier_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name="Thu ngân").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersecurityprofile'),
    ]

    operations = [
        migrations.RunPython(delete_cashier_group, migrations.RunPython.noop),
    ]
