# Generated by Django 4.2.24 on 2026-06-05 08:37

from django.db import migrations


def delete_stock_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name="Kho").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_cashier_group'),
    ]

    operations = [
        migrations.RunPython(delete_stock_group, migrations.RunPython.noop),
    ]
