# Generated by Codex on 2026-06-07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_stock_group"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="securityevent",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Nhật ký thao tác",
                "verbose_name_plural": "Nhật ký thao tác",
                "permissions": [
                    ("view_dashboard", "Có thể xem dashboard hệ thống"),
                    ("view_support_conversation", "Có thể xem hội thoại hỗ trợ"),
                    ("manage_support_conversation", "Có thể xử lý hội thoại hỗ trợ"),
                    ("view_payroll", "Có thể xem tính lương"),
                    ("manage_payroll", "Có thể quản lý tính lương"),
                    ("run_database_backup", "Có thể tạo bản sao lưu dữ liệu"),
                ],
            },
        ),
    ]
