# Generated by Django 4.2.30 on 2026-06-02 15:08

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinic', '0012_add_salary_and_shift_coefficients'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('payslip_code', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Mã phiếu lương')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Tháng')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Năm')),
                ('hourly_rate', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tiền một giờ (snapshot)')),
                ('doctor_coefficient', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Hệ số bác sĩ (snapshot)')),
                ('total_converted_hours', models.DecimalField(decimal_places=4, default=Decimal('0'), editable=False, max_digits=10, verbose_name='Tổng giờ quy đổi')),
                ('total_amount', models.DecimalField(decimal_places=0, default=Decimal('0'), editable=False, max_digits=14, verbose_name='Tổng tiền làm thêm (VNĐ)')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('confirmed', 'Đã xác nhận'), ('paid', 'Đã thanh toán')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payslips', to=settings.AUTH_USER_MODEL, verbose_name='Người lập phiếu')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='clinic.staff', verbose_name='Bác sĩ')),
            ],
            options={
                'verbose_name': 'Phiếu lương',
                'verbose_name_plural': 'Phiếu lương',
                'ordering': ['-year', '-month', 'doctor__full_name'],
                'unique_together': {('doctor', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='SalaryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('hourly_rate', models.DecimalField(decimal_places=0, help_text='Mức tiền cơ bản trả cho 1 giờ quy đổi.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Số tiền một giờ (VNĐ)')),
                ('effective_from', models.DateField(help_text='Cấu hình này có hiệu lực từ ngày đã chọn trở đi.', verbose_name='Áp dụng từ')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Cấu hình lương cơ bản',
                'verbose_name_plural': 'Cấu hình lương cơ bản',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='PaySlipEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('shift_hours', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Số giờ ca trực')),
                ('shift_coefficient', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('2.0'))], verbose_name='Hệ số ca (snapshot)')),
                ('patient_coefficient_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tổng hệ số bệnh nhân')),
                ('converted_hours', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8, verbose_name='Giờ quy đổi')),
                ('line_total', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=14, verbose_name='Thành tiền (VNĐ)')),
                ('doctor_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslip_entries', to='clinic.doctorschedule', verbose_name='Ca trực')),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='payroll.payslip', verbose_name='Phiếu lương')),
            ],
            options={
                'verbose_name': 'Chi tiết phiếu lương',
                'verbose_name_plural': 'Chi tiết phiếu lương',
                'ordering': ['doctor_schedule__work_date', 'doctor_schedule__shift__start_time'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentComplexity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('complexity_coefficient', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='0.0 = thông thường; 0.1–0.5 = phức tạp.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('0.50'))], verbose_name='Hệ số phức tạp')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Lý do / ghi chú')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='complexity', to='clinic.appointment', verbose_name='Lượt khám')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_complexities', to=settings.AUTH_USER_MODEL, verbose_name='Người nhập')),
            ],
            options={
                'verbose_name': 'Hệ số ca phức tạp',
                'verbose_name_plural': 'Hệ số ca phức tạp',
                'ordering': ['-appointment__doctor_schedule__work_date'],
            },
        ),
    ]
