# Generated by Django 4.2.24 on 2026-04-30 06:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('name', models.CharField(max_length=150, verbose_name='Tên bảng giá')),
                ('effective_from', models.DateField(verbose_name='Áp dụng từ')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Áp dụng đến')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang áp dụng')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Bảng giá dịch vụ',
                'verbose_name_plural': 'Bảng giá dịch vụ',
                'ordering': ['-effective_from', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('code', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Mã danh mục')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Tên danh mục')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
            ],
            options={
                'verbose_name': 'Danh mục dịch vụ',
                'verbose_name_plural': 'Danh mục dịch vụ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('employee_code', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Mã số')),
                ('role', models.CharField(choices=[('doctor', 'Bác sĩ'), ('assistant', 'Trợ thủ nha khoa'), ('receptionist', 'Lễ tân'), ('technician', 'Kỹ thuật viên'), ('manager', 'Quản lý'), ('other', 'Khác')], default='doctor', max_length=30, verbose_name='Chức danh')),
                ('full_name', models.CharField(max_length=150, verbose_name='Họ tên')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('primary_workplace', models.CharField(blank=True, max_length=255, verbose_name='Nơi công tác chính thức')),
                ('degree', models.CharField(blank=True, max_length=255, verbose_name='Bằng cấp / học hàm học vị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang làm việc')),
            ],
            options={
                'verbose_name': 'Nhân viên / bác sĩ',
                'verbose_name_plural': 'Nhân viên / bác sĩ',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('code', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Mã dịch vụ')),
                ('name', models.CharField(max_length=200, verbose_name='Tên dịch vụ')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Thời lượng dự kiến (phút)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='clinic.servicecategory', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Dịch vụ',
                'verbose_name_plural': 'Dịch vụ',
                'ordering': ['category__name', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Đơn giá')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='clinic.pricelist', verbose_name='Bảng giá')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='clinic.service', verbose_name='Dịch vụ')),
            ],
            options={
                'verbose_name': 'Giá dịch vụ',
                'verbose_name_plural': 'Giá dịch vụ',
                'ordering': ['service__category__name', 'service__name'],
                'unique_together': {('price_list', 'service')},
            },
        ),
    ]
