# Generated by Django 4.2.30 on 2026-04-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('patient_code', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Mã bệnh nhân')),
                ('full_name', models.CharField(max_length=150, verbose_name='Họ và tên')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('gender', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], default='male', max_length=10, verbose_name='Giới tính')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ')),
                ('occupation', models.CharField(blank=True, max_length=150, verbose_name='Nghề nghiệp')),
                ('allergy_note', models.TextField(blank=True, verbose_name='Dị ứng / ghi chú y tế')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú khác')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
            ],
            options={
                'verbose_name': 'Bệnh nhân',
                'verbose_name_plural': 'Bệnh nhân',
                'ordering': ['full_name'],
            },
        ),
    ]
