# Generated by Django 4.2.24 on 2026-05-09 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('date', models.DateField(unique=True, verbose_name='Ngày nghỉ')),
                ('name', models.CharField(max_length=150, verbose_name='Tên ngày nghỉ')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang áp dụng')),
            ],
            options={
                'verbose_name': 'Ngày nghỉ',
                'verbose_name_plural': 'Ngày nghỉ',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('name', models.CharField(max_length=120, verbose_name='Tên ca')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Thứ hai'), (1, 'Thứ ba'), (2, 'Thứ tư'), (3, 'Thứ năm'), (4, 'Thứ sáu'), (5, 'Thứ bảy'), (6, 'Chủ nhật')], verbose_name='Ngày làm việc')),
                ('start_time', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('end_time', models.TimeField(verbose_name='Giờ kết thúc')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Ca làm việc',
                'verbose_name_plural': 'Ca làm việc',
                'ordering': ['weekday', 'start_time', 'name'],
                'unique_together': {('weekday', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('work_date', models.DateField(verbose_name='Ngày trực')),
                ('status', models.CharField(choices=[('registered', 'Đã đăng ký'), ('cancelled', 'Đã hủy'), ('completed', 'Đã hoàn tất')], default='registered', max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_schedules', to='clinic.staff', verbose_name='Bác sĩ')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_schedules', to='clinic.workshift', verbose_name='Ca làm việc')),
            ],
            options={
                'verbose_name': 'Lịch trực bác sĩ',
                'verbose_name_plural': 'Lịch trực bác sĩ',
                'ordering': ['-work_date', 'shift__start_time', 'doctor__full_name'],
                'unique_together': {('doctor', 'work_date', 'shift')},
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('appointment_code', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Mã lịch khám')),
                ('start_time', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('end_time', models.TimeField(verbose_name='Giờ kết thúc')),
                ('status', models.CharField(choices=[('scheduled', 'Đã đặt'), ('confirmed', 'Đã xác nhận'), ('checked_in', 'Đã đến'), ('completed', 'Hoàn tất'), ('cancelled', 'Đã hủy'), ('no_show', 'Không đến')], default='scheduled', max_length=20, verbose_name='Trạng thái')),
                ('chief_complaint', models.CharField(blank=True, max_length=255, verbose_name='Lý do khám')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('doctor_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clinic.doctorschedule', verbose_name='Lịch trực bác sĩ')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clinic.patient', verbose_name='Bệnh nhân')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clinic.service', verbose_name='Dịch vụ dự kiến')),
            ],
            options={
                'verbose_name': 'Lịch khám',
                'verbose_name_plural': 'Lịch khám',
                'ordering': ['-doctor_schedule__work_date', 'start_time', 'patient__full_name'],
            },
        ),
    ]
