# Generated by Codex on 2026-05-13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0003_clinicholiday_workshift_doctorschedule_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="blood_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Chưa rõ"),
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                max_length=3,
                verbose_name="Nhóm máu",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="current_medications",
            field=models.TextField(blank=True, verbose_name="Thuốc đang sử dụng"),
        ),
        migrations.AddField(
            model_name="patient",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="Người liên hệ khẩn cấp"),
        ),
        migrations.AddField(
            model_name="patient",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=30, verbose_name="SĐT khẩn cấp"),
        ),
        migrations.AddField(
            model_name="patient",
            name="medical_history",
            field=models.TextField(blank=True, verbose_name="Tiền sử bệnh"),
        ),
        migrations.AddField(
            model_name="patient",
            name="national_id",
            field=models.CharField(blank=True, max_length=30, verbose_name="CCCD / CMND"),
        ),
        migrations.AddField(
            model_name="staff",
            name="address",
            field=models.CharField(blank=True, max_length=255, verbose_name="Địa chỉ"),
        ),
        migrations.AddField(
            model_name="staff",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="Người liên hệ khẩn cấp"),
        ),
        migrations.AddField(
            model_name="staff",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=30, verbose_name="SĐT khẩn cấp"),
        ),
        migrations.AddField(
            model_name="staff",
            name="experience_years",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(80)],
                verbose_name="Số năm kinh nghiệm",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Nam"), ("female", "Nữ"), ("other", "Khác")],
                max_length=10,
                verbose_name="Giới tính",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="license_number",
            field=models.CharField(blank=True, max_length=80, verbose_name="Số chứng chỉ hành nghề"),
        ),
        migrations.AddField(
            model_name="staff",
            name="note",
            field=models.TextField(blank=True, verbose_name="Ghi chú"),
        ),
        migrations.AddField(
            model_name="staff",
            name="specialization",
            field=models.CharField(blank=True, max_length=255, verbose_name="Chuyên môn"),
        ),
        migrations.AddField(
            model_name="staff",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Ngày bắt đầu làm việc"),
        ),
    ]
