# Generated by Django 4.2.24 on 2026-05-12 19:37

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_patient_staff_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('invoice_code', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Mã hóa đơn')),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Ngày lập')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Ngày hẹn thanh toán')),
                ('payment_type', models.CharField(choices=[('one_time', 'Thanh toán một lần'), ('installment', 'Trả góp')], default='one_time', max_length=20, verbose_name='Hình thức thanh toán')),
                ('total_amount', models.DecimalField(decimal_places=0, default=Decimal('0'), editable=False, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tổng chi phí')),
                ('paid_amount', models.DecimalField(decimal_places=0, default=Decimal('0'), editable=False, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Đã thanh toán')),
                ('status', models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('paid', 'Đã thanh toán'), ('outstanding', 'Còn nợ')], default='unpaid', editable=False, max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='clinic.appointment', verbose_name='Lịch khám')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clinic.patient', verbose_name='Bệnh nhân')),
            ],
            options={
                'verbose_name': 'Hóa đơn',
                'verbose_name_plural': 'Hóa đơn',
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('medicine_code', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Mã thuốc')),
                ('name', models.CharField(max_length=150, verbose_name='Tên thuốc')),
                ('active_ingredient', models.CharField(blank=True, max_length=150, verbose_name='Hoạt chất')),
                ('strength', models.CharField(blank=True, max_length=80, verbose_name='Hàm lượng')),
                ('unit', models.CharField(blank=True, max_length=40, verbose_name='Đơn vị')),
                ('usage_note', models.TextField(blank=True, verbose_name='Hướng dẫn chung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
            ],
            options={
                'verbose_name': 'Thuốc',
                'verbose_name_plural': 'Thuốc',
                'ordering': ['name', 'strength'],
                'unique_together': {('name', 'strength')},
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('prescription_code', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Mã đơn thuốc')),
                ('prescribed_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Ngày kê đơn')),
                ('diagnosis', models.CharField(blank=True, max_length=255, verbose_name='Chẩn đoán')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='clinic.appointment', verbose_name='Lịch khám')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='clinic.staff', verbose_name='Bác sĩ kê đơn')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='clinic.patient', verbose_name='Bệnh nhân')),
            ],
            options={
                'verbose_name': 'Đơn thuốc',
                'verbose_name_plural': 'Đơn thuốc',
                'ordering': ['-prescribed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('dosage', models.CharField(max_length=150, verbose_name='Liều dùng')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số lượng')),
                ('instructions', models.TextField(verbose_name='Hướng dẫn sử dụng')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='clinic.medicine', verbose_name='Thuốc')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinic.prescription', verbose_name='Đơn thuốc')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn thuốc',
                'verbose_name_plural': 'Chi tiết đơn thuốc',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('paid_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Ngày thanh toán')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Số tiền')),
                ('method', models.CharField(choices=[('cash', 'Tiền mặt'), ('transfer', 'Chuyển khoản'), ('card', 'Thẻ'), ('other', 'Khác')], default='cash', max_length=20, verbose_name='Phương thức')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='clinic.invoice', verbose_name='Hóa đơn')),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Thanh toán',
                'ordering': ['-paid_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Nội dung điều trị')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Đơn giá')),
                ('line_total', models.DecimalField(decimal_places=0, default=Decimal('0'), editable=False, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Thành tiền')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinic.invoice', verbose_name='Hóa đơn')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='clinic.service', verbose_name='Dịch vụ')),
            ],
            options={
                'verbose_name': 'Chi tiết hóa đơn',
                'verbose_name_plural': 'Chi tiết hóa đơn',
                'ordering': ['id'],
            },
        ),
    ]
