# Generated by Django 4.2.24 on 2026-05-12 20:44

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_invoice_medicine_prescription_prescriptionitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('supply_code', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Mã vật tư')),
                ('name', models.CharField(max_length=150, verbose_name='Tên vật tư')),
                ('category', models.CharField(choices=[('consumable', 'Vật tư tiêu hao'), ('injection', 'Kim tiêm / gây tê'), ('medicine', 'Thuốc / dung dịch'), ('restorative', 'Vật liệu phục hồi'), ('sterilization', 'Khử khuẩn'), ('instrument', 'Dụng cụ'), ('other', 'Khác')], default='consumable', max_length=30, verbose_name='Nhóm vật tư')),
                ('unit', models.CharField(max_length=40, verbose_name='Đơn vị tính')),
                ('minimum_quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ngưỡng cảnh báo tồn')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
            ],
            options={
                'verbose_name': 'Vật tư',
                'verbose_name_plural': 'Vật tư',
                'ordering': ['category', 'name'],
                'unique_together': {('name', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='SupplyLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('lot_number', models.CharField(blank=True, max_length=80, verbose_name='Số lô')),
                ('supplier', models.CharField(blank=True, max_length=150, verbose_name='Nhà cung cấp')),
                ('received_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Ngày nhập')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Hạn sử dụng')),
                ('initial_quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Số lượng nhập')),
                ('current_quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tồn hiện tại')),
                ('unit_cost', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Đơn giá nhập')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='clinic.supply', verbose_name='Vật tư')),
            ],
            options={
                'verbose_name': 'Lô vật tư',
                'verbose_name_plural': 'Lô vật tư',
                'ordering': ['expiry_date', 'received_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupplyExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('export_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Ngày xuất')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Số lượng xuất')),
                ('used_for', models.CharField(blank=True, max_length=255, verbose_name='Mục đích sử dụng')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exports', to='clinic.supplylot', verbose_name='Lô vật tư')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_exports', to='clinic.staff', verbose_name='Người thực hiện')),
            ],
            options={
                'verbose_name': 'Phiếu xuất vật tư',
                'verbose_name_plural': 'Phiếu xuất vật tư',
                'ordering': ['-export_date', '-id'],
            },
        ),
    ]
