# Generated by Django 4.2.24 on 2026-05-25 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clinic", "0006_supply_supplylot_supplyexport"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="arrival_type",
            field=models.CharField(
                choices=[("scheduled", "Có lịch hẹn"), ("walk_in", "Không hẹn trước")],
                default="scheduled",
                max_length=20,
                verbose_name="Nguồn tiếp nhận",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="checked_in_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Thời điểm tiếp đón"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="checked_in_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checked_in_appointments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Lễ tân tiếp đón",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="queue_number",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Số thứ tự tiếp đón"),
        ),
    ]
