# Generated by Django 4.2.24 on 2026-05-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0007_appointment_reception_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="priority_level",
            field=models.CharField(
                choices=[("normal", "Bình thường"), ("priority", "Ưu tiên"), ("urgent", "Khẩn")],
                default="normal",
                max_length=20,
                verbose_name="Mức độ ưu tiên",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="visit_type",
            field=models.CharField(
                choices=[
                    ("new", "Khám mới"),
                    ("follow_up", "Tái khám"),
                    ("treatment", "Điều trị theo liệu trình"),
                    ("emergency", "Cấp cứu"),
                    ("warranty", "Bảo hành"),
                ],
                default="new",
                max_length=20,
                verbose_name="Phân loại lượt khám",
            ),
        ),
    ]
