# Generated by Django 4.2.24 on 2026-05-25 00:00

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0008_appointment_visit_type_priority_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("cash", "Tiền mặt"),
                    ("transfer", "Chuyển khoản"),
                    ("card", "Thẻ"),
                    ("momo", "MoMo"),
                    ("other", "Khác"),
                ],
                default="cash",
                max_length=20,
                verbose_name="Phương thức",
            ),
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật")),
                (
                    "provider",
                    models.CharField(
                        choices=[("momo", "MoMo")],
                        default="momo",
                        max_length=20,
                        verbose_name="Cổng thanh toán",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Đang chờ"),
                            ("success", "Thành công"),
                            ("failed", "Thất bại"),
                            ("review", "Cần kiểm tra"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Trạng thái giao dịch",
                    ),
                ),
                ("order_id", models.CharField(max_length=80, unique=True, verbose_name="Mã giao dịch đối tác")),
                ("request_id", models.CharField(max_length=80, unique=True, verbose_name="Mã request")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(Decimal("1"))],
                        verbose_name="Số tiền",
                    ),
                ),
                ("customer_email", models.EmailField(blank=True, max_length=254, verbose_name="Email nhận biên nhận")),
                ("pay_url", models.URLField(blank=True, max_length=500, verbose_name="Liên kết thanh toán")),
                ("deeplink", models.CharField(blank=True, max_length=500, verbose_name="Deeplink")),
                ("qr_code_url", models.CharField(blank=True, max_length=1000, verbose_name="Dữ liệu QR")),
                ("trans_id", models.CharField(blank=True, max_length=80, verbose_name="Mã giao dịch MoMo")),
                ("result_code", models.IntegerField(blank=True, null=True, verbose_name="Mã kết quả")),
                (
                    "provider_message",
                    models.CharField(blank=True, max_length=255, verbose_name="Thông điệp cổng thanh toán"),
                ),
                ("raw_create_response", models.JSONField(blank=True, default=dict, verbose_name="Phản hồi tạo giao dịch")),
                ("raw_ipn_payload", models.JSONField(blank=True, default=dict, verbose_name="Payload IPN")),
                ("redirect_payload", models.JSONField(blank=True, default=dict, verbose_name="Payload redirect")),
                ("paid_at", models.DateTimeField(blank=True, null=True, verbose_name="Thời điểm thanh toán thành công")),
                (
                    "receipt_email_sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Thời điểm gửi mail biên nhận"),
                ),
                ("receipt_email_error", models.TextField(blank=True, verbose_name="Lỗi gửi mail")),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to="clinic.invoice",
                        verbose_name="Hóa đơn",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_transaction",
                        to="clinic.payment",
                        verbose_name="Thanh toán đã ghi nhận",
                    ),
                ),
            ],
            options={
                "verbose_name": "Giao dịch cổng thanh toán",
                "verbose_name_plural": "Giao dịch cổng thanh toán",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
