# Generated by Django 4.2.24 on 2026-06-02 15:31

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_add_salary_and_shift_coefficients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='salary_coefficient',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('1.30'), help_text='Theo học hàm học vị: Đại học=1.3, Thạc sĩ=1.5, Tiến sĩ=1.7, PGS=2.0, GS=2.5', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.50')), django.core.validators.MaxValueValidator(Decimal('5.00'))], verbose_name='Hệ số bác sĩ'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='shift_coefficient',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('1.00'), help_text='Trong giờ hành chính: 1.0. Ngoài giờ / cuối tuần: 1.1–1.5', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('2.00'))], verbose_name='Hệ số ca'),
        ),
    ]
